name: Lint Ruby

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FROZEN: true
      BUNDLE_GEMFILE: gemfiles/rubocop.gemfile
      CI: true
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Lint Ruby code with RuboCop
      run: |
        bundle exec rubocop
